name: Build Custom AMI

on:
  push:
    branches:
      - implement  

jobs:
  build-ami:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: setup-packer
        with:
          packer-version: latest

      - name: Set up AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build Custom AMI
        run: |
          packer validate /home/devops/devops-project/packer-project/application.json
          packer build /home/devops/devops-project/packer-project/application.json