name: Build and Test

on:
  push:
    branches:
      - implement
  pull_request:
    branches:
      - implement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.416

    - name: Build
      run: dotnet build HelloWorldApp/HelloWorld.csproj

    - name: Test
      run: dotnet test HelloWorldApp/HelloWorld.csproj